//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryBuilderMVC.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start FREE.
        /// </summary>
        public static string IndexStartFREE {
            get {
                return ResourceManager.GetString("IndexStartFREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the opportunity to see.
        /// </summary>
        public static string IndexTextAboutErModel1 {
            get {
                return ResourceManager.GetString("IndexTextAboutErModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a detailed ER-model of your database..
        /// </summary>
        public static string IndexTextAboutErModel2 {
            get {
                return ResourceManager.GetString("IndexTextAboutErModel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be save to popular format.
        /// </summary>
        public static string IndexTextAboutExportData1 {
            get {
                return ResourceManager.GetString("IndexTextAboutExportData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files on your PC or send to e-mail..
        /// </summary>
        public static string IndexTextAboutExportData2 {
            get {
                return ResourceManager.GetString("IndexTextAboutExportData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the ability to share your project with.
        /// </summary>
        public static string IndexTextAboutShared1 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colleagues and build queries together or just give.
        /// </summary>
        public static string IndexTextAboutShared2 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someone access requests in your project..
        /// </summary>
        public static string IndexTextAboutShared3 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND EXCEL.
        /// </summary>
        public static string IndexTextAndExcel {
            get {
                return ResourceManager.GetString("IndexTextAndExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build query.
        /// </summary>
        public static string IndexTextBuildQuery {
            get {
                return ResourceManager.GetString("IndexTextBuildQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to build your requests only with the mouse. You do not need to know the SQL to build your query and get results. For this will be enough to use our intuitive graphical interface..
        /// </summary>
        public static string IndexTextBuildQueryText {
            get {
                return ResourceManager.GetString("IndexTextBuildQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        public static string IndexTextDATABASE {
            get {
                return ResourceManager.GetString("IndexTextDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER-model your database.
        /// </summary>
        public static string IndexTextER {
            get {
                return ResourceManager.GetString("IndexTextER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER-MODEL.
        /// </summary>
        public static string IndexTextErModel {
            get {
                return ResourceManager.GetString("IndexTextErModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the opportunity to see a detailed ER-model of your database. The ER-model will help you to trace all the connections and relationships of tables, as well as the available fields..
        /// </summary>
        public static string IndexTextERText {
            get {
                return ResourceManager.GetString("IndexTextERText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT DATA.
        /// </summary>
        public static string IndexTextEXPORTDATA {
            get {
                return ResourceManager.GetString("IndexTextEXPORTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string IndexTextExportDataSmall {
            get {
                return ResourceManager.GetString("IndexTextExportDataSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity to export result for your query in *.XLS and *.PDF. Your data will be save to popular format files on your PC or send to e-mail..
        /// </summary>
        public static string IndexTextExportDataText {
            get {
                return ResourceManager.GetString("IndexTextExportDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string IndexTextGettingStarted {
            get {
                return ResourceManager.GetString("IndexTextGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Builder can use without registration. For use just press &quot;START FREE&quot;. Query Builder without registration have features such us:.
        /// </summary>
        public static string IndexTextGettinStartedText {
            get {
                return ResourceManager.GetString("IndexTextGettinStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More ».
        /// </summary>
        public static string IndexTextMore {
            get {
                return ResourceManager.GetString("IndexTextMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        public static string IndexTextProject {
            get {
                return ResourceManager.GetString("IndexTextProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different types of queries.
        /// </summary>
        public static string IndexTextQueries {
            get {
                return ResourceManager.GetString("IndexTextQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to build various types of queries, requests and combine to make nested queries.Complex queries are now easy to build..
        /// </summary>
        public static string IndexTextQueriesText {
            get {
                return ResourceManager.GetString("IndexTextQueriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARED.
        /// </summary>
        public static string IndexTextShared {
            get {
                return ResourceManager.GetString("IndexTextShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared project.
        /// </summary>
        public static string IndexTextSharedProject {
            get {
                return ResourceManager.GetString("IndexTextSharedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the ability to share your project with colleagues and build queries together or just give someone access requests in your project..
        /// </summary>
        public static string IndexTextSharedProjectText {
            get {
                return ResourceManager.GetString("IndexTextSharedProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to PDF.
        /// </summary>
        public static string IndexTextToPDF {
            get {
                return ResourceManager.GetString("IndexTextToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SQLQueryBuilder.
        /// </summary>
        public static string IndexTextWelcome {
            get {
                return ResourceManager.GetString("IndexTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR.
        /// </summary>
        public static string IndexTextYOUR {
            get {
                return ResourceManager.GetString("IndexTextYOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter project name.
        /// </summary>
        public static string ProjectValidationMessage {
            get {
                return ResourceManager.GetString("ProjectValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string ProjectValidationMessageDescription {
            get {
                return ResourceManager.GetString("ProjectValidationMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit length string for 150 symbols.
        /// </summary>
        public static string ProjectValidationMessageDescriptionMaxLenght {
            get {
                return ResourceManager.GetString("ProjectValidationMessageDescriptionMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit length string for 16 letters.
        /// </summary>
        public static string ProjectValidationMessageMaxLenght {
            get {
                return ResourceManager.GetString("ProjectValidationMessageMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings .
        /// </summary>
        public static string SettingsForMenu {
            get {
                return ResourceManager.GetString("SettingsForMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string WorkflowMenuSettings {
            get {
                return ResourceManager.GetString("WorkflowMenuSettings", resourceCulture);
            }
        }
    }
}
