//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.DataModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsShare
    {
        public int ProjectID { get; set; }
        public string SharedEmail { get; set; }
        public int Delflag { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
