//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ResultHistory
{
    public string ResultName { get; set; }
    public string ResultOwner { get; set; }
    public int ConnectionID { get; set; }
    public string ResultBody { get; set; }
    public int Delflag { get; set; }

    public virtual ConnectionDB ConnectionDB { get; set; }
}
