// <auto-generated />
namespace QueryBuilder.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
#pragma warning disable 0436

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPropertyFromUserIdToTableProjectShare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPropertyFromUserIdToTableProjectShare));
        
        string IMigrationMetadata.Id
        {
            get { return "201604111047046_AddPropertyFromUserIdToTableProjectShare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
